title: Aryan Sheoran
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "asheoran.me" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Aryan Sheoran # add your name
author-img: david-freeman.jpg # add your photo
about-author: I’m someone who thrives on curiosity. In the realm of coding and computer science, I’m just starting out with C. 💻 It’s an exciting journey as I build a solid foundation in programming. To complement this, I’m also diving into JavaScript to expand my web development skills and enhance my portfolio.
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: aryan-sheoran # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
